Fix build on aarch64
Before, (e.g. on macos-latest job which is now run on aarch64):

```
In file included from include/crc32c_portable.cc:10:0: error:

In file included from include/crc32c_prefetch.h:18:0: error:

/Applications/Xcode_15.0.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/15.0.0/include/xmmintrin.h:14:2: error:
     error: "This header is only meant to be used on x86 and x64 architecture"
   |
14 | #error "This header is only meant to be used on x86 and x64 architecture"
   |  ^
```

The problem is that HAVE_MM_PREFETCH was always enabled,
though it should only be enabled on x86_64 platforms.